sudo: required
language: python
services:
- docker
env:
- distro=alpine
- distro=ubuntu
stages:
- test
- name: deploy
  if: branch = develop
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo sh -c 'echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release
  -cs) stable" > /etc/apt/sources.list.d/docker.list'
- sudo apt-get update -o Dir::Etc::sourcelist=/etc/apt/sources.list.d/docker.list
- sudo apt-get -y install docker-ce
- docker version
install: true
script:
- docker image build --no-cache --pull --tag test-${distro} ${distro}/
- docker container run --rm --workdir /root --name ${distro} test-${distro} env
- docker image ls
after_failure:
- docker container logs --details ${distro}
after_success:
- docker image history test-${distro}
jobs:
  include:
  - stage: deploy
    env:
    - distro=all
    before_install: true
    install: true
    script:
    - ".travis/deploy.sh"
    after_failure: true
    after_success: true
branches:
  except:
  - master
notifications:
  slack:
    secure: WFXIuHp1CYCZBEfVzVmCjI3rOqduSbhU1fGVWKkFRiaJ1ttP11VjvGakLrsqZi61nnF/FaJCwCvlf0JXpQcDzzYCsu19oKBTsYdNGkH/lNFeGziYgwDGd/gsZFjS3HOr3XsapDV6Y4OTA/Wrf0kH6D2a7voS/Qx2obG4h5t9labpqjD4VpooIJbOWc3fYiSblZmaE/bQQcxkTEEnqhe2RtdhqWj6qxfHW7eIDOlWUwSwBqlvb4M2tlgwyIyBLG8Pq0/X6p5GwL7zmCLcpWb961TD1CVHMXYGoU4lSn5SuYJgiOzoheQj8Fd+E9nK+RIe2DrqQ57cv1JLLaS8GGRo/u62L5+lEReNBGe4ciFTH0KP8uqrXDgX+AMl7tkxqCSDK1iBypHRyd3vVN0aasYnPIJH+sWOKhnrCWXT3Ck+GYf11mp+0EPSqZRNXcUCHQ2bWG8pZvzjBYndZ9pl3DwZz3F6kFtSFkCJGxvHDgWGBFq2TzVZDQ9NyTY4U4kB7bFRP52ET5xYu4LO32la/04d/PyM7B7ncoW8yXTIwlCAGasiwehhQbUTwB3bm+5gZKsvqDivxrcoYADxwqOieCeFZWupJ1tUUiRz++9uhzrhrBd4bDBjAtEPfS3dZyqiZwPNv4MYVcTxSV/ktRlt7EdN2ZhYrKOG5/Y23YobvO1sOPU=
  on_success: always
  on_failure: always
