sudo: required
language: python
services:
- docker
env:
- distro=alpine
- distro=ubuntu
stages:
- test
- name: deploy
  if: branch = develop
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo sh -c 'echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release
  -cs) stable" > /etc/apt/sources.list.d/docker.list'
- sudo apt-get update -o Dir::Etc::sourcelist=/etc/apt/sources.list.d/docker.list
- sudo apt-get -y install docker-ce
- docker version
install: true
script:
- docker image build --no-cache --pull --tag test-${distro} ${distro}/
- docker container run --rm --workdir /root --name ${distro}
  test-${distro} env
- docker image ls
after_failure:
- docker container logs --details ${distro}
after_success:
- docker image history test-${distro}
jobs:
  include:
  - stage: deploy
    env:
    - distro=all
    before_install: true
    install: true
    script:
    - ".travis/deploy.sh"
    after_failure: true
branches:
  except:
  - master
